
__all__=[
    #kr
    "TransE",
    "TransH",
    "TransR",
    "TransD",
    "TransA",
    "RotatE",
    "Rescal",
    "SimplE",
    "TuckER",
    "KEPLER",
    "PairRE",
    "BoxE",
    "ComplEx",
    "DistMult",
    "TransE_Adapter",
    "TransE_baseline",
    "TransE_Add_Description",
    "TransE_Add_Time",
    "TransE_Add_Type",
    "TransE_Add_Path"
]